version: "3.9"
services:
  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    command: mongod

# mongodb://root:secret@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
